name: Playwright Test Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-playwright-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install
          
      - name: Run Playwright tests
        run: |
         npx playwright install-deps
         npx playwright test --reporter=json --reporter=html

      - name: Upload JSON test results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: test-results/test-results.json

      - name: Upload HTML test report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: test-results/html-report
